const errorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEFAULT: 'DEFAULT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  EMAIL_ALREADY_EXISTED: 'EMAIL_ALREADY_EXISTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};

module.exports = {
  errorCodes,
};
