const errorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEFAULT: 'DEFAULT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  EMAIL_ALREADY_EXISTED: 'EMAIL_ALREADY_EXISTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ID_PARAM_NOT_VALID_OBJECT_ID: 'ID_PARAM_NOT_VALID_OBJECT_ID',
  CAR_BRAND_NAME_NOT_UNIQUE: 'CAR_BRAND_NAME_NOT_UNIQUE',
  CAR_BRAND_NOT_FOUND: 'CAR_BRAND_NOT_FOUND',
  EXTRA_FEATURE_NAME_NOT_UNIQUE: 'EXTRA_FEATURE_NAME_NOT_UNIQUE',
  EXTRA_FEATURE_NOT_FOUND: 'EXTRA_FEATURE_NOT_FOUND',
  CAR_MODEL_NOT_FOUND: 'CAR_MODEL_NOT_FOUND',
  CAR_MODEL_NAME_MUST_BE_UNIQUE_PER_BRAND: 'CAR_MODEL_NAME_MUST_BE_UNIQUE_PER_BRAND',
  CAR_NOT_FOUND: 'CAR_NOT_FOUND',
  CAR_PLATE_NUMBER_NOT_UNIQUE: 'CAR_PLATE_NUMBER_NOT_UNIQUE',
};

module.exports = {
  errorCodes,
};
