const errorCodes = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEFAULT: 'DEFAULT',
  LOGIN_ERROR: 'LOGIN_ERROR',
  EMAIL_ALREADY_EXISTED: 'EMAIL_ALREADY_EXISTED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ID_PARAM_NOT_VALID_OBJECT_ID: 'ID_PARAM_NOT_VALID_OBJECT_ID',
  CAR_BRAND_NAME_NOT_UNIQUE: 'CAR_BRAND_NAME_NOT_UNIQUE',
  CAR_BRAND_NOT_FOUND: 'CAR_BRAND_NOT_FOUND',
};

module.exports = {
  errorCodes,
};
